### ISSUE TITLE
Грамматическая ошибка

### ISSUE THREAD

**Issue by fairay** [Epsilonbolee0/Hacking_to_the_Gate#2]
У вас za worl видно, Вы в курсе?
![image](https://user-images.githubusercontent.com/48217178/53918351-ce6c4a00-4077-11e9-8942-dca713340047.png)
```python
root = Tk()

Label(root, text = "Hello worl").pack()
```

3c719150
@Epsilonbolee0

**Comment by Epsilonbolee0** [comment]
Заметил за ВАРУДУ, больше не повторится. 

Прилагаю номер ревизии.

![image](https://user-images.githubusercontent.com/46526694/53918972-9960f700-4079-11e9-9d24-43fccf273df8.png)


f387b35
@fairay
