### ISSUE TITLE
Ошибка запуска

### ISSUE THREAD

**Issue by fairay** [Epsilonbolee0/Hacking_to_the_Gate#3]
boat_layer.py не запускается (ошибка на стоке 81)
commit 9dc6411703287c076f2ac40be92c46a2ad14f3f3

**Comment by Epsilonbolee0** [comment]
Здравствуй, @fairay!

Ошибка запуска состояла в том, что я декларировал в файле `components.py` параметр компонента `HasSolidity` двояко - я называл его то `__undefeated`, то `undefeated.`

Ревизия стабильной версии на данный момент - d90887aceec3fcc02a5743f6e59e2078629ef0e1

Благодарю завнимательность!
